### ISSUE TITLE
How can I enable the insiders mkdocs-material features?

### ISSUE THREAD

**Issue by jamesone** [backstage/mkdocs-techdocs-core#65]
- https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor - If I am a sponsor, is it possible to pull the insiders features through the mkdocs-techdocs-core plugin?

**Comment by realabja** [comment]
Hi all, I am interested to see if this would work as well @jamesone have you tried insiders?

**Comment by llwt** [comment]
I would imagine you would need to make a private fork of this repo to consume the private fork of the `mkdocs-material` insider package, then consumer that private fork in your builder image/process instead of the standard `techdocs-core` package.

I'm interested in this as well if anyone else has gone about it. I might end up going down this route for our company and will report back if we do.
